
services:
  orders_panel_db:
    image: postgres:15
    restart: always # Esto le dice a Docker que si el contenedor falla por alguna razón (por ejemplo, después de un reinicio del sistema), debe intentar reiniciarlo automáticamente.
    env_file:
      - .env
    volumes:
      - postgres_app_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  
  orders_panel_redis:
    image: redis:latest
    restart: always
    ports:
      - "6382:6379"
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lfu
  orders_panel_app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    restart: always
    depends_on:
      - orders_panel_db
      - orders_panel_redis
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
  
volumes:
  postgres_app_data: